version: '{branch}.{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  CLCACHE_SERVER: 1
  PACKAGES: boost-filesystem boost-signals2 boost-test libevent openssl zeromq berkeleydb secp256k1 leveldb
  PYTHONIOENCODING: utf-8
cache:
- C:\tools\vcpkg\installed
- C:\Users\appveyor\clcache
init:
- cmd: set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%
install:
- cmd: pip install git+https://github.com/frerich/clcache.git
# Disable zmq test for now since python zmq library on Windows would cause Access violation sometimes.
# - cmd: pip install zmq
- ps:  $packages = $env:PACKAGES -Split ' '
- ps:  for ($i=0; $i -lt $packages.length; $i++) {
           $env:ALL_PACKAGES += $packages[$i] + ":" + $env:PLATFORM + "-windows-static "
       }
- cmd: git -C C:\Tools\vcpkg pull # This is a temporary fix, can be removed after appveyor update its image to include Microsoft/vcpkg#4046
- cmd: C:\Tools\vcpkg\bootstrap-vcpkg.bat
- cmd: vcpkg remove --recurse --outdated
- cmd: vcpkg install %ALL_PACKAGES%
- cmd: del /s /q C:\Tools\vcpkg\installed\%PLATFORM%-windows-static\debug # Remove unused debug library
before_build:
- ps:  clcache -M 536870912
- cmd: python build_msvc\msvc-autogen.py
- ps:  $files = (Get-ChildItem -Recurse | where {$_.extension -eq ".vcxproj"}).FullName
- ps:  for (${i} = 0; ${i} -lt ${files}.length; ${i}++) {
           ${content} = (Get-Content ${files}[${i}]);
           ${content} = ${content}.Replace("</RuntimeLibrary>", "</RuntimeLibrary><DebugInformationFormat>None</DebugInformationFormat>");
           ${content} = ${content}.Replace("<WholeProgramOptimization>true", "<WholeProgramOptimization>false");
           ${content} = ${content}.Replace("NDEBUG;", "");
           Set-Content ${files}[${i}] ${content};
       }
- ps:  Start-Process clcache-server
- ps:  fsutil behavior set disablelastaccess 0 # Enable Access time feature on Windows (for clcache)
build_script:
- cmd: msbuild /p:TrackFileAccess=false /p:CLToolExe=clcache.exe build_msvc\bitcoin.sln /m /v:q /nowarn:C4244;C4267;C4715 /nologo
after_build:
- ps:  fsutil behavior set disablelastaccess 0 # Disable Access time feature on Windows (better performance)
- ps:  clcache -z
before_test:
- ps:  ${conf_ini} = (Get-Content([IO.Path]::Combine(${env:APPVEYOR_BUILD_FOLDER}, "test", "config.ini.in")))
- ps:  ${conf_ini} = ${conf_ini}.Replace("@abs_top_srcdir@", ${env:APPVEYOR_BUILD_FOLDER})
- ps:  ${conf_ini} = ${conf_ini}.Replace("@abs_top_builddir@", ${env:APPVEYOR_BUILD_FOLDER})
- ps:  ${conf_ini} = ${conf_ini}.Replace("@EXEEXT@", ".exe")
- ps:  ${conf_ini} = ${conf_ini}.Replace("@ENABLE_WALLET_TRUE@", "")
- ps:  ${conf_ini} = ${conf_ini}.Replace("@BUILD_BITCOIN_CLI_TRUE@", "")
- ps:  ${conf_ini} = ${conf_ini}.Replace("@BUILD_BITCOIND_TRUE@", "")
- ps:  ${conf_ini} = ${conf_ini}.Replace("@ENABLE_ZMQ_TRUE@", "")
- ps:  ${utf8} = New-Object System.Text.UTF8Encoding ${false}
- ps:  '[IO.File]::WriteAllLines([IO.Path]::Combine(${env:APPVEYOR_BUILD_FOLDER}, "test", "config.ini"), ${conf_ini}, ${utf8})'
- ps:  move "build_msvc\${env:PLATFORM}\${env:CONFIGURATION}\*.exe" src
test_script:
- cmd: src\test_bitcoin.exe
- ps:  src\bench_bitcoin.exe -evals=1 -scaling=0
- ps:  python test\util\bitcoin-util-test.py
- cmd: python test\util\rpcauth-test.py
- cmd: python test\functional\test_runner.py --ci --force --quiet --combinedlogslen=4000
deploy: off
