blank_issues_enabled: true
contact_links:
  - name: Snailcoin Core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Snailcoin Core Developers
    url: https://bitcoincore.org
    about: Snailcoin Core homepage
