blank_issues_enabled: true
contact_links:
  - name: Tortoisecoin Core Security Policy
    url: https://github.com/tortoisecoin/tortoisecoin/blob/master/SECURITY.md
    about: View security policy
  - name: Tortoisecoin Core Developers
    url: https://tortoisecoincore.org
    about: Tortoisecoin Core homepage
