[package]
name = "cuckoofilter-cabi"
version = "0.4.0"
license = "MIT"
authors = [
    "Florian Jacob <accounts+git@florianjacob.de>"
]
homepage = "http://geekyogre.com"
repository = "https://github.com/seiflotfy/rust-cuckoofilter"
description = """
C interface wrapper for cuckoofilter, a library for
the Bloom filter replacement for approximated set-membership queries.
"""
keywords = ["bloomfilter", "cuckoohashing", "cuckoofilter"]

build = "build.rs"

[dependencies]
cuckoofilter = { version = "0.5", path = "../" }

[build-dependencies]
cbindgen = "0.19.0"

[lib]
# foreign programs can link against cdylib or staticlib to use rust-cuckoofilter's C API
crate-type = ["cdylib", "staticlib"]
