[package]
name = "libc-test"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies.libc]
path = ".."
default-features = false

[build-dependencies]
cc = "1.0"
ctest = "0.2"

[features]
default = [ "std" ]
std = [ "libc/std" ]
align = [ "libc/align" ]
extra_traits = [ "libc/extra_traits" ]

[[test]]
name = "main"
path = "test/main.rs"
harness = false

[[test]]
name = "linux-fcntl"
path = "test/linux_fcntl.rs"
harness = false

[[test]]
name = "linux-ipv6"
path = "test/linux_ipv6.rs"
harness = false

[[test]]
name = "linux-elf"
path = "test/linux_elf.rs"
harness = false

[[test]]
name = "linux-strerror_r"
path = "test/linux_strerror_r.rs"
harness = false

[[test]]
name = "linux-termios"
path = "test/linux_termios.rs"
harness = false

[[test]]
name = "cmsg"
path = "test/cmsg.rs"
harness = true
