name: Build depends

on:
  workflow_call:
    inputs:
      build-target:
        description: "Target name as defined by matrix.sh"
        required: true
        type: string
      container-path:
        description: "Path to built container at registry"
        required: true
        type: string
    outputs:
      key:
        description: "Key needed for restoring depends cache"
        value: ${{ jobs.build-depends.outputs.key }}

jobs:
  build-depends:
    name: Build depends
    runs-on: ubuntu-24.04
    outputs:
      key:  ${{ steps.restore.outputs.cache-primary-key }}
    container:
      image: ${{ inputs.container-path }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Initial setup
        id: setup
        run: |
          BUILD_TARGET="${{ inputs.build-target }}"
          source ./ci/dash/matrix.sh
          echo "DEP_OPTS=${DEP_OPTS}" >> "${GITHUB_OUTPUT}"
          echo "HOST=${HOST}" >> "${GITHUB_OUTPUT}"
          DEP_HASH="$(echo -n "${BUILD_TARGET}" "${DEP_OPTS}" "${HOST}" | sha256sum | head -c 64)"
          echo "\"${BUILD_TARGET}\" has HOST=\"${HOST}\" and DEP_OPTS=\"${DEP_OPTS}\" with hash \"${DEP_HASH}\""
          echo "DEP_HASH=${DEP_HASH}" >> "${GITHUB_OUTPUT}"

        shell: bash

      - name: Cache depends sources
        uses: actions/cache@v4
        with:
          path: |
            depends/sources
          key: depends-sources-${{ hashFiles('depends/packages/*') }}
          restore-keys: |
            depends-sources-

      - name: Cache SDKs
        uses: actions/cache@v4
        if: inputs.build-target == 'mac'
        with:
          path: |
            depends/SDKs
          key: depends-sdks-${{ hashFiles('depends/hosts/darwin.mk') }}
          restore-keys: |
            depends-sdks-

      - name: Restore cached depends
        uses: actions/cache/restore@v4
        id: restore
        with:
          path: |
            depends/built
            depends/${{ steps.setup.outputs.HOST }}
          key: depends-${{ hashFiles('contrib/containers/ci/Dockerfile') }}-${{ inputs.build-target }}-${{ steps.setup.outputs.DEP_HASH }}-${{ hashFiles('depends/packages/*') }}
          restore-keys: |
            depends-${{ hashFiles('contrib/containers/ci/Dockerfile') }}-${{ inputs.build-target }}-${{ steps.setup.outputs.DEP_HASH }}-
            depends-${{ hashFiles('contrib/containers/ci/Dockerfile') }}-${{ inputs.build-target }}-

      - name: Build depends
        run: |
          export HOST="${{ steps.setup.outputs.HOST  }}"
          if [ "${HOST}" = "x86_64-apple-darwin" ]; then
            ./contrib/containers/guix/scripts/setup-sdk
          fi
          env ${{ steps.setup.outputs.DEP_OPTS }} make -j$(nproc) -C depends

      - name: Save depends cache
        uses: actions/cache/save@v4
        if: steps.restore.outputs.cache-hit != 'true'
        with:
          path: |
            depends/built
            depends/${{ steps.setup.outputs.HOST }}
          key: ${{ steps.restore.outputs.cache-primary-key }}
