name: CI

on:
  push:
  pull_request_target:

permissions:
  contents: read
  packages: write

env:
  DOCKER_DRIVER: overlay2
  FAST_MODE: false

jobs:
  container:
    name: Build container
    uses: ./.github/workflows/build-container.yml

  depends-arm-linux:
    name: arm-linux-gnueabihf
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    with:
      build-target: arm-linux
      container-path: ${{ needs.container.outputs.path }}

  depends-linux64:
    name: x86_64-pc-linux-gnu
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    with:
      build-target: linux64
      container-path: ${{ needs.container.outputs.path }}

  depends-linux64_multiprocess:
    name: x86_64-pc-linux-gnu_multiprocess
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    with:
      build-target: linux64_multiprocess
      container-path: ${{ needs.container.outputs.path }}

  depends-linux64_nowallet:
    name: x86_64-pc-linux-gnu_nowallet
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    with:
      build-target: linux64_nowallet
      container-path: ${{ needs.container.outputs.path }}

  depends-win64:
    name: x86_64-w64-mingw32
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    with:
      build-target: win64
      container-path: ${{ needs.container.outputs.path }}

  src-arm-linux:
    name: arm-linux-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-arm-linux]
    with:
      build-target: arm-linux
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-arm-linux.outputs.key }}

  src-linux64:
    name: linux64-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    with:
      build-target: linux64
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_cxx20:
    name: linux64_cxx20-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    with:
      build-target: linux64_cxx20
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_fuzz:
    name: linux64_fuzz-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    with:
      build-target: linux64_fuzz
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_multiprocess:
    name: linux64_multiprocess-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64_multiprocess]
    with:
      build-target: linux64_multiprocess
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64_multiprocess.outputs.key }}

  src-linux64_nowallet:
    name: linux64_nowallet-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64_nowallet]
    with:
      build-target: linux64_nowallet
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64_nowallet.outputs.key }}

  src-linux64_sqlite:
    name: linux64_sqlite-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    with:
      build-target: linux64_sqlite
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_tsan:
    name: linux64_tsan-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    with:
      build-target: linux64_tsan
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-linux64_ubsan:
    name: linux64_ubsan-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-linux64]
    with:
      build-target: linux64_ubsan
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-linux64.outputs.key }}

  src-win64:
    name: win64-build
    uses: ./.github/workflows/build-src.yml
    needs: [container, depends-win64]
    with:
      build-target: win64
      container-path: ${{ needs.container.outputs.path }}
      depends-key: ${{ needs.depends-win64.outputs.key }}
