name: Docker CD

on:
  push:
    branches:
    - master
    - develop

  pull_request:
    branches:
    - master

jobs:
  ubuntu-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get snapshot hash, version & branch
        id: snapshot
        run: |
          echo "::set-env name=GIT_HASH::$(git rev-parse --short=7 "$GITHUB_SHA")"
          echo "::set-env name=LAST_TAG::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "::set-env name=COMMITS_AHEAD::$(git rev-list $(git describe --tags $(git rev-list --tags --max-count=1)).. --count)"
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
          echo "::set-env name=TAGS::$(if [ "${{ github.event_name }}" == "push" ] && [ "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" == "master" ]; then echo "latest,$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; elif [ "${{ github.event_name }}" == "pull_request" ]; then echo ""; else echo "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; fi)"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: veriblock/vbtc
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          tags: "${{ env.TAGS }},${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }},${{ github.sha }}"
      - name: Show Tags
        run: |
          echo "Successfully pushed the following tags:"
          echo "----"
          echo "$(IFS=',' read -ra TAGS <<< "$(if [ "${{ github.event_name }}" == "push" ] && [ "${{ env.BRANCH }}" == "master" ]; then echo "latest,${{ env.BRANCH }}"; elif [ "${{ github.event_name }}" == "pull_request" ]; then echo ""; else echo "${{ env.BRANCH }}"; fi)"; for i in "${TAGS[@]}"; do echo $i; done)"
          echo "${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }}"
          echo "${{ github.sha }}"
          echo "----"

  alpine-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get snapshot hash, version & branch
        id: snapshot
        run: |
          echo "::set-env name=GIT_HASH::$(git rev-parse --short=7 "$GITHUB_SHA")"
          echo "::set-env name=LAST_TAG::$(git describe --tags $(git rev-list --tags --max-count=1))"
          echo "::set-env name=COMMITS_AHEAD::$(git rev-list $(git describe --tags $(git rev-list --tags --max-count=1)).. --count)"
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
          echo "::set-env name=TAGS::$(if [ "${{ github.event_name }}" == "push" ] && [ "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" == "master" ]; then echo "latest,$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; elif [ "${{ github.event_name }}" == "pull_request" ]; then echo ""; else echo "$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"; fi)"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          dockerfile: alpine.Dockerfile
          name: veriblock/vbitcoin
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          tags: "${{ env.TAGS }},${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }},${{ github.sha }}"
      - name: Show Tags
        run: |
          echo "Successfully pushed the following tags:"
          echo "----"
          echo "$(IFS=',' read -ra TAGS <<< "$(if [ "${{ github.event_name }}" == "push" ] && [ "${{ env.BRANCH }}" == "master" ]; then echo "latest,${{ env.BRANCH }}"; elif [ "${{ github.event_name }}" == "pull_request" ]; then echo ""; else echo "${{ env.BRANCH }}"; fi)"; for i in "${TAGS[@]}"; do echo $i; done)"
          echo "${{ env.LAST_TAG }}-${{ env.BRANCH }}.${{ env.COMMITS_AHEAD }}-${{ env.GIT_HASH }}"
          echo "${{ github.sha }}"
          echo "----"
