name: Fast CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container: veriblock/btcdev
    env:
      CC: gcc
      CXX: g++
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
        --without-gui
        --enable-werror
        --enable-lcov
        --enable-lcov-branch-coverage
        --disable-bench

    - name: make
      run: make -j2
    - name: make check
      timeout-minutes: 10
      run: make check
    - name: Collect coverage
      run: lcov -c -d src -o cov.info
    - name: Run sonarqube
      run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}