name: Guix Build

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'guix-build')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Commit variables
        id: dockerfile
        run: |
          echo "::set-output name=hash::$(sha256sum ./contrib/containers/guix/Dockerfile | cut -d ' ' -f1)"
          echo "::set-output name=host_user_id::$(id -u)"
          echo "::set-output name=host_group_id::$(id -g)"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.dockerfile.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          build-args: |
            USER_ID=${{ steps.dockerfile.outputs.host_user_id }}
            GROUP_ID=${{ steps.dockerfile.outputs.host_group_id }}
          build-contexts: |
            docker_root=${{ github.workspace }}/contrib/containers/guix
          file: ./contrib/containers/guix/Dockerfile
          load: true
          tags: guix_ubuntu:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run Guix build
        run: |
          docker run --privileged -d --rm -t \
            --name guix-daemon \
            -e ADDITIONAL_GUIX_COMMON_FLAGS='--max-jobs=32' \
            -v ${{ github.workspace }}:/src/dash \
            -w /src/dash \
            guix_ubuntu:latest && \
          docker exec guix-daemon bash -c "/usr/local/bin/guix-start"

      - name: Ensure build passes
        run: |
          if [[ $? != 0 ]]; then
            echo "Guix build failed!"
            exit 1
          fi
      - name: Compute SHA256 checksums for binaries
        run: |
          ( \
          SRC_PATH_PREFIX=guix-build-$(git rev-parse --short=12 HEAD)/distsrc- && \
          sha256sum ${SRC_PATH_PREFIX}*/src/dash{d,-cli,-tx,-wallet}{,.exe} && \
          sha256sum ${SRC_PATH_PREFIX}*/src/qt/dash-qt{,.exe} && \
          sha256sum ${SRC_PATH_PREFIX}*/src/test/test_dash{,.exe} \
          ) | sort -k 2
      - name: Compute SHA256 checksums for archives
        run: |
          find guix-build-"$(git rev-parse --short=12 HEAD)"/output -type f | grep -v SHA256 | xargs sha256sum | sort -k 2
